import React, { useState } from 'react';
import { GlassCard } from '../components/GlassCard';
import './Pages.css';

export const InteractiveLab: React.FC = () => {
  const [selectedPair1, setSelectedPair1] = useState<string | null>(null);
  const [selectedPair2, setSelectedPair2] = useState<string | null>(null);
  const [selectedPair3, setSelectedPair3] = useState<string | null>(null);

  return (
    <div className="page-container">
      <header className="hero-section">
        <h1 className="gradient-text">Interactive Comparison Lab</h1>
        <p className="hero-subtitle">
          Test your perception. Compare human vs. AI and analyze dependencies.
        </p>
      </header>

      <div className="content-section lab-pair">
        <GlassCard>
          <h2>1. When does a tool become a crutch?</h2>
          <p>Select the scenario that represents healthy AI integration:</p>
          <div className="lab-options">
            <div 
              className={`glass-panel lab-option-card ${selectedPair1 === 'A' ? 'selected' : ''}`}
              onClick={() => setSelectedPair1('A')}
            >
              <strong>Scenario A:</strong> A manager automatically approves a budget report generated by an AI workspace assistant without reviewing the calculations, assuming the machine doesn't make math errors.
            </div>
            <div 
              className={`glass-panel lab-option-card ${selectedPair1 === 'B' ? 'selected' : ''}`}
              onClick={() => setSelectedPair1('B')}
            >
              <strong>Scenario B:</strong> A manager uses an AI assistant to aggregate data, but manually checks the math and sources before presenting it to the board.
            </div>
          </div>
          {selectedPair1 && (
            <div className="feedback-text" style={{ color: selectedPair1 === 'B' ? 'var(--color-tertiary)' : 'var(--color-error)' }}>
              {selectedPair1 === 'A' ? 'Incorrect. This represents automation bias and cognitive debt.' : 'Correct! This is a healthy use of AI as an accelerant, not a crutch.'}
            </div>
          )}
        </GlassCard>
      </div>

      <div className="content-section lab-pair">
        <GlassCard>
          <h2>2. Guess which one was made by AI?</h2>
          <p>Read the two news reports about the Mayon Volcano and select the one generated by AI:</p>
          <div className="lab-options">
            <div 
              className={`glass-panel lab-option-card ${selectedPair2 === 'A' ? 'selected' : ''}`}
              onClick={() => setSelectedPair2('A')}
            >
              <strong>Report A:</strong> ALBAY, Philippines — Hundreds of families were evacuated after sudden volcanic activity from Mayon Volcano blanketed several communities in ash over the weekend... (General statements, repetitive structure, no direct quotes)
            </div>
            <div 
              className={`glass-panel lab-option-card ${selectedPair2 === 'B' ? 'selected' : ''}`}
              onClick={() => setSelectedPair2('B')}
            >
              <strong>Report B:</strong> MANILA, Philippines (AP) — More than 300 families have been evacuated after massive amounts of ash billowed from the Mayon volcano over the weekend... “The ashfall was just so thick and there was zero visibility even in our national road,” Mayor Caloy Baldo said.
            </div>
          </div>
          {selectedPair2 && (
            <div className="feedback-text" style={{ color: selectedPair2 === 'A' ? 'var(--color-tertiary)' : 'var(--color-error)' }}>
              {selectedPair2 === 'A' ? 'Correct! Report A lacks specific quotes and nuances typical of human journalism.' : 'Incorrect. Report B includes specific quotes and nuanced human reporting (AP News).'}
            </div>
          )}
        </GlassCard>
      </div>

      <div className="content-section lab-pair">
        <GlassCard>
          <h2>3. Guess which text on Bamboo was made by AI?</h2>
          <p>Read the two informative texts about Bamboo and select the one generated by AI:</p>
          <div className="lab-options">
            <div 
              className={`glass-panel lab-option-card ${selectedPair3 === 'A' ? 'selected' : ''}`}
              onClick={() => setSelectedPair3('A')}
            >
              <strong>Text A:</strong> Bamboos are a type of grass that gets often mistaken as a plant or tree. There are about 1500 different species of bamboo which typically grow in subregions of China, South America and Africa (Elliott, 2023). They are presently known to be an eco-friendly alternative...
            </div>
            <div 
              className={`glass-panel lab-option-card ${selectedPair3 === 'B' ? 'selected' : ''}`}
              onClick={() => setSelectedPair3('B')}
            >
              <strong>Text B:</strong> Bamboo, though commonly mistaken for a tree, is actually a fast-growing grass with roughly 1,500 species distributed across regions like Asia, South America, and Africa. Recently, it has emerged as a sustainable substitute for plastic materials...
            </div>
          </div>
          {selectedPair3 && (
            <div className="feedback-text" style={{ color: selectedPair3 === 'B' ? 'var(--color-tertiary)' : 'var(--color-primary)' }}>
              {selectedPair3 === 'B' ? 'Correct. Text B represents a common AI rewriting style, smoothing out human quirks and removing the inline citations present in Text A.' : 'Incorrect. Text A includes human-like phrasing and inline citations.'}
            </div>
          )}
        </GlassCard>
      </div>

    </div>
  );
};
