import React, { useState } from 'react';
import { GlassCard } from '../components/GlassCard';
import { Tooltip } from '../components/Tooltip';
import { ParallaxSection, ParallaxImage } from '../components/ParallaxSection';
import { HoverImage } from '../components/HoverImage';
import './Lab.css';

export const LabSection: React.FC = () => {
  const [selectedPair1, setSelectedPair1] = useState<string | null>(null);
  const [selectedPair2, setSelectedPair2] = useState<string | null>(null);
  const [selectedPair3, setSelectedPair3] = useState<string | null>(null);

  return (
    <section id="lab" className="page-section lab-section">
      <ParallaxSection>
        <div className="section-divider"></div>
        <h2 className="section-heading">
          <span className="gradient-text">Interactive Comparison Lab</span>
        </h2>
        <p className="section-intro">
          Test your perception. Can you tell human from machine? Click a scenario to reveal the answer.
        </p>
      </ParallaxSection>

      <ParallaxSection delay={0.1} className="section-image-wrapper" style={{ marginBottom: 'var(--spacing-2xl)' }}>
        <ParallaxImage 
          src="/ai-divide/images/1 - interactive lab hero.jpg" 
          alt="Code on a dark terminal screen" 
          height="320px"
        />
      </ParallaxSection>

      {/* Pair 1: Tool vs Crutch */}
      <ParallaxSection mode="spotlight" style={{ marginBottom: 'var(--spacing-xl)' }}>
        <GlassCard>
          <HoverImage 
            src="/ai-divide/images/2 - tool vs crutch.jpg" 
            alt="Modern laptop on desk with glowing screen" 
            className="card-img"
          />
          <h2>1. When does a tool become a crutch?</h2>
          <p>Select the scenario that represents <strong>healthy</strong> AI integration:</p>
          <div className="lab-options">
            <div 
              className={`lab-option-card glass-panel ${selectedPair1 === 'A' ? 'selected wrong' : ''}`}
              onClick={() => setSelectedPair1('A')}
            >
              <strong>Scenario A:</strong> A manager automatically approves a budget report generated by an AI workspace assistant without reviewing the calculations, assuming the machine doesn't make math errors.
            </div>
            <div 
              className={`lab-option-card glass-panel ${selectedPair1 === 'B' ? 'selected correct' : ''}`}
              onClick={() => setSelectedPair1('B')}
            >
              <strong>Scenario B:</strong> A manager uses an AI assistant to aggregate data, but manually checks the math and sources before presenting it to the board.
            </div>
          </div>
          {selectedPair1 && (
            <div className={`feedback-text ${selectedPair1 === 'B' ? 'correct' : 'wrong'}`}>
              {selectedPair1 === 'A' 
                ? '✗ Incorrect. This represents automation bias and cognitive debt.' 
                : '✓ Correct! This is a healthy use of AI as an accelerant, not a crutch.'}
            </div>
          )}
        </GlassCard>
      </ParallaxSection>

      {/* Pair 2: AI vs Human News */}
      <ParallaxSection mode="spotlight" style={{ marginBottom: 'var(--spacing-xl)' }}>
        <GlassCard>
          <HoverImage 
            src="/ai-divide/images/3 - ai vs human news.jpg" 
            alt="Newspaper close-up" 
            className="card-img"
          />
          <h2>2. Guess which report was made by AI</h2>
          <p>Read the two news reports about the Mayon Volcano. Which one was generated by an AI?</p>
          <div className="lab-options">
            <div 
              className={`lab-option-card glass-panel ${selectedPair2 === 'A' ? 'selected correct' : ''}`}
              onClick={() => setSelectedPair2('A')}
            >
              <strong>Report A:</strong> ALBAY, Philippines — Hundreds of families were evacuated after sudden volcanic activity from Mayon Volcano blanketed several communities in ash over the weekend... (General statements, repetitive structure, no direct quotes)
            </div>
            <div 
              className={`lab-option-card glass-panel ${selectedPair2 === 'B' ? 'selected wrong' : ''}`}
              onClick={() => setSelectedPair2('B')}
            >
              <strong>Report B:</strong> MANILA, Philippines (AP) — More than 300 families have been evacuated after massive amounts of ash billowed from the Mayon volcano... "The ashfall was just so thick and there was zero visibility even in our national road," Mayor Caloy Baldo said.
            </div>
          </div>
          {selectedPair2 && (
            <div className={`feedback-text ${selectedPair2 === 'A' ? 'correct' : 'wrong'}`}>
              {selectedPair2 === 'A' ? (
                <>✓ Correct! Report A lacks specific quotes and nuances typical of human journalism.</>
              ) : (
                <>✗ Incorrect. Report B includes specific quotes and nuanced human reporting (<Tooltip content="Associated Press, a reputable global news agency.">AP News</Tooltip>).</>
              )}
            </div>
          )}
        </GlassCard>
      </ParallaxSection>

      {/* Pair 3: Bamboo Text */}
      <ParallaxSection mode="spotlight">
        <GlassCard>
          <HoverImage 
            src="/ai-divide/images/4 - bamboo ai vs human.jpg" 
            alt="Bamboo forest" 
            className="card-img"
          />
          <h2>3. Which text on Bamboo was written by AI?</h2>
          <p>Read the two informative texts about bamboo. Which one was rewritten by AI?</p>
          <div className="lab-options lab-options-grid">
            <div 
              className={`lab-option-card glass-panel ${selectedPair3 === 'A' ? 'selected wrong' : ''}`}
              onClick={() => setSelectedPair3('A')}
            >
              <strong>Text A:</strong> Bamboos are a type of grass that gets often mistaken as a plant or tree. There are about 1500 different species of bamboo which typically grow in subregions of China, South America and Africa (<Tooltip content="Elliott (2023) - Research on bamboo biodiversity and distribution.">Elliott, 2023</Tooltip>). They are presently known to be an eco-friendly alternative...
            </div>
            <div 
              className={`lab-option-card glass-panel ${selectedPair3 === 'B' ? 'selected correct' : ''}`}
              onClick={() => setSelectedPair3('B')}
            >
              <strong>Text B:</strong> Bamboo, though commonly mistaken for a tree, is actually a fast-growing grass with roughly 1,500 species distributed across regions like Asia, South America, and Africa. Recently, it has emerged as a sustainable substitute for plastic materials...
            </div>
          </div>
          {selectedPair3 && (
            <div className={`feedback-text ${selectedPair3 === 'B' ? 'correct' : 'wrong'}`}>
              {selectedPair3 === 'B' ? (
                <>✓ Correct. Text B represents a common AI rewriting style — smoothing out human quirks and removing inline citations.</>
              ) : (
                <>✗ Incorrect. Text A includes human-like phrasing and inline citations (<Tooltip content="Huang (2024), Stemmann (2023)">sources</Tooltip>).</>
              )}
            </div>
          )}
        </GlassCard>
      </ParallaxSection>
    </section>
  );
};
